sudo: false

language: python

python:
- '3.4'

services:
- postgresql

addons:
  postgresql: "9.5"
  apt:
      packages:
          - postgresql-9.5-postgis-2.3

env:
  global:
  - DB_USER=postgres

branches:
  only:
    - master

install:
- pip install --upgrade pip
- pip install cython
- pip install python-coveralls
- pip install pytest-cov
- pip install -r requirements-dev.txt
- python setup.py develop

before_script:
- psql -U postgres -c "CREATE DATABASE test_ban;"
- psql -U postgres -c "create extension postgis;" -d test_ban
- psql -U postgres -c "create extension hstore;" -d test_ban
- psql -U postgres -c "create extension unaccent;" -d test_ban

after_success:
  - coveralls

script: py.test --cov=ban/

notifications:
  irc:
    channels:
    - irc.freenode.net##ban
    on_success: change
    on_failure: always
  email: false
